In [1]:
import numpy as np
import pandas as pd

In [11]:
population = np.random.randint(10,20,100)

In [12]:
population

array([18, 18, 13, 17, 17, 10, 14, 12, 15, 12, 12, 12, 11, 10, 18, 14, 10,
       19, 16, 12, 14, 11, 15, 13, 14, 14, 13, 17, 11, 11, 17, 17, 10, 12,
       19, 19, 13, 12, 15, 18, 11, 10, 17, 16, 12, 10, 18, 12, 15, 11, 18,
       11, 15, 14, 12, 18, 13, 15, 10, 19, 13, 16, 13, 14, 17, 16, 13, 19,
       10, 14, 14, 15, 17, 16, 16, 12, 14, 12, 17, 11, 16, 16, 10, 17, 12,
       13, 15, 14, 12, 14, 13, 17, 19, 10, 10, 15, 19, 16, 16, 15])

In [14]:
np.mean(population)

14.2

In [16]:
np.median(population)

14.0

In [19]:
mode(population)

NameError: name 'mode' is not defined

In [20]:
s1= np.random.choice(population,15)   # s--> samples in popuplation and we have taken 4 samples
s2= np.random.choice(population,15)
s3=np.random.choice(population,15)
s4= np.random.choice(population,15)

In [21]:
s1

array([10, 18, 10, 11, 17, 13, 14, 18, 19, 10, 14, 10, 19, 10, 11])

In [22]:
s2

array([15, 10, 19, 19, 15, 14, 12, 15, 14, 17, 17, 11, 16, 10, 19])

In [23]:
s3

array([12, 15, 18, 16, 12, 19, 13, 10, 10, 11, 13, 19, 19, 10, 17])

In [24]:
s4

array([12, 12, 12, 18, 18, 12, 14, 11, 14, 10, 10, 11, 10, 10, 12])

In [25]:
samples=[s1,s2,s3,s4]

In [27]:
samples

[array([10, 18, 10, 11, 17, 13, 14, 18, 19, 10, 14, 10, 19, 10, 11]),
 array([15, 10, 19, 19, 15, 14, 12, 15, 14, 17, 17, 11, 16, 10, 19]),
 array([12, 15, 18, 16, 12, 19, 13, 10, 10, 11, 13, 19, 19, 10, 17]),
 array([12, 12, 12, 18, 18, 12, 14, 11, 14, 10, 10, 11, 10, 10, 12])]

In [30]:
samples_mean=[]
for i in samples:
    samples_mean.append(np.mean(i))


In [31]:
samples_mean

[13.6, 14.866666666666667, 14.266666666666667, 12.4]

In [32]:
samples_mean=np.mean(samples_mean)

In [33]:
samples_mean

13.783333333333333

measure of spread:

In [35]:
list1=[1,2,34,6,90,10,7,23,15,20,21,22,25,3,4,9]

In [40]:
std=np.std(list1)

In [39]:
m=np.mean(list1)

In [48]:
z_score=[]
for i in sorted(list1):    # sorted list--> means it is converting intlo asscending order
    z= (i-m)/std
    z_score.append(z)

In [49]:
z_score

[-0.8290419314102148,
 -0.7809815295893328,
 -0.7329211277684508,
 -0.6848607259475687,
 -0.5887399223058047,
 -0.5406795204849227,
 -0.4445587168431587,
 -0.39649831502227667,
 -0.15619630591786657,
 0.08410570318654353,
 0.13216610500742554,
 0.18022650682830757,
 0.22828690864918957,
 0.3244077122909536,
 0.7569513286788918,
 3.4483338306482847]

In [55]:
z_score1={}
for i in sorted(list1):
    # sorted list--> means it is converting intlo asscending order
    sume=i-m
    z= sume/std
    z_score1.update({i:z})

In [56]:
z_score1

{1: -0.8290419314102148,
 2: -0.7809815295893328,
 3: -0.7329211277684508,
 4: -0.6848607259475687,
 6: -0.5887399223058047,
 7: -0.5406795204849227,
 9: -0.4445587168431587,
 10: -0.39649831502227667,
 15: -0.15619630591786657,
 20: 0.08410570318654353,
 21: 0.13216610500742554,
 22: 0.18022650682830757,
 23: 0.22828690864918957,
 25: 0.3244077122909536,
 34: 0.7569513286788918,
 90: 3.4483338306482847}

Quartile

In [57]:
Q1= np.percentile(list1,25)

In [58]:
Q1

5.5

In [59]:
Q2= np.percentile(list1,50)
Q2

12.5

In [60]:
np.median(list1)

12.5

In [61]:
Q3= np.percentile(list1,75)
Q3

22.25