In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
#plt.style.use('seaborn')
import nltk # natural language tool-kit
import re

In [2]:
with open('F://indexing.txt', mode='r') as f:
    text= f.read()

doc = text.split('\n') # converts into list

In [3]:
doc

['Virat smashed another ton in One day International',
 'Rohit Sharma is highest run score in T20 International',
 'Gold prices rise high, after sharp fall',
 'Farms fires in Punjab, seven times more than in Haryana',
 '']

In [4]:
df = pd.DataFrame(doc,columns=['documents'])
df.drop(index=4,axis=0,inplace=True)

In [5]:
Q = 'Who got highest runs in cricket'  # query

### Text Normalization:
- Lower
- Remove special Characters

In [6]:
def textprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9 ]','',text)
    return text

In [7]:
df['doc_tp']= df['documents'].apply(textprocess)

AttributeError: module 'tensorflow' has no attribute 'version'

In [8]:
df

documents  \
0  Virat smashed another ton in One day Internati...   
1  Rohit Sharma is highest run score in T20 Inter...   
2            Gold prices rise high, after sharp fall   
3  Farms fires in Punjab, seven times more than i...   

                                              doc_tp  
0  virat smashed another ton in one day internati...  
1  rohit sharma is highest run score in t20 inter...  
2             gold prices rise high after sharp fall  
3  farms fires in punjab seven times more than in...

**Lemmatizatiom**
- process of extracting root word

In [9]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to C:\Users\Home
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [10]:
from nltk.stem import wordnet    #pretrained RNN

In [11]:
lema = wordnet.WordNetLemmatizer()  # intializing lemma

In [12]:
lema.lemmatize('loving',pos='v')
#n-noun, v-verb,r-adverb,a-adjective...etc

'love'

In [13]:
#parts of speech tagging:(pos)

In [14]:
from nltk import pos_tag

In [15]:
sent = df['doc_tp'][0]
sent

'virat smashed another ton in one day international'

In [16]:
import nltk
nltk.download('universal_tagset')

[nltk_data] Downloading package universal_tagset to C:\Users\Home
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Package universal_tagset is already up-to-date!


True

In [17]:
from nltk import pos_tag
tag_list = pos_tag(nltk.word_tokenize(sent),tagset=None)   # tagset = 'universal'
print(tag_list)

[('virat', 'NN'), ('smashed', 'VBD'), ('another', 'DT'), ('ton', 'NN'), ('in', 'IN'), ('one', 'CD'), ('day', 'NN'), ('international', 'JJ')]


In [18]:
# google pos tag list in nltk:

In [19]:
lema.lemmatize('smashed',pos='v')

'smash'

In [20]:
for sent1 in df['doc_tp']:
    from nltk import pos_tag
    x=pos_tag(nltk.word_tokenize(sent1),tagset=None)
    print(x)

[('virat', 'NN'), ('smashed', 'VBD'), ('another', 'DT'), ('ton', 'NN'), ('in', 'IN'), ('one', 'CD'), ('day', 'NN'), ('international', 'JJ')]
[('rohit', 'NN'), ('sharma', 'NN'), ('is', 'VBZ'), ('highest', 'JJS'), ('run', 'NN'), ('score', 'NN'), ('in', 'IN'), ('t20', 'JJ'), ('international', 'JJ')]
[('gold', 'NN'), ('prices', 'NNS'), ('rise', 'VBP'), ('high', 'JJ'), ('after', 'IN'), ('sharp', 'JJ'), ('fall', 'NN')]
[('farms', 'NNS'), ('fires', 'NNS'), ('in', 'IN'), ('punjab', 'NN'), ('seven', 'CD'), ('times', 'NNS'), ('more', 'JJR'), ('than', 'IN'), ('in', 'IN'), ('haryana', 'NN')]


In [46]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
print(stop)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [26]:
def sent_lema(sentence):
    #computing parts of speech
    tag_list= pos_tag(nltk.word_tokenize(sentence),
                      tagset=None)
    lema_sent =[]# initializing empty list
    for token,pos_token in tag_list:
        if token in stop: # removing stopwords
            continue
            
        if pos_token.startswith('V'): #verb
            pos_val='v'
        elif pos_token.startswith('J'):  #adjective
            pos_val='a'
        elif pos_token.startswith('R'): #adverb
            pos_val= 'r'
        else:  # any pos except verb, adj , adverb
            pos_val='n'

        lema_token = lema.lemmatize(token,pos_val)# computing
        lema_sent.append(lema_token)#append values in list
    return " ".join(lema_sent)

In [27]:
print('Clean Text:',sent)
print('Lemmatization clean Text:',sent_lema(sent))

Clean Text: virat smashed another ton in one day international
Lemmatization clean Text: virat smash another ton one day international


In [28]:
df['doc_lemma']= df['doc_tp'].apply(sent_lema)
df.head()

documents  \
0  Virat smashed another ton in One day Internati...   
1  Rohit Sharma is highest run score in T20 Inter...   
2            Gold prices rise high, after sharp fall   
3  Farms fires in Punjab, seven times more than i...   

                                              doc_tp  \
0  virat smashed another ton in one day internati...   
1  rohit sharma is highest run score in t20 inter...   
2             gold prices rise high after sharp fall   
3  farms fires in punjab seven times more than in...   

                                       doc_lemma  
0  virat smash another ton one day international  
1  rohit sharma high run score t20 international  
2                gold price rise high sharp fall  
3            farm fire punjab seven time haryana

In [29]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Home
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [30]:
#from nltk.corpus import stopwords

In [31]:
#stop = stopwords.words('english')
#print(stop)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [32]:
df

documents  \
0  Virat smashed another ton in One day Internati...   
1  Rohit Sharma is highest run score in T20 Inter...   
2            Gold prices rise high, after sharp fall   
3  Farms fires in Punjab, seven times more than i...   

                                              doc_tp  \
0  virat smashed another ton in one day internati...   
1  rohit sharma is highest run score in t20 inter...   
2             gold prices rise high after sharp fall   
3  farms fires in punjab seven times more than in...   

                                       doc_lemma  
0  virat smash another ton one day international  
1  rohit sharma high run score t20 international  
2                gold price rise high sharp fall  
3            farm fire punjab seven time haryana

### Word Embedding:
- Bag of words

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()
X= cv.fit_transform(df['doc_lemma']).toarray()   # converting text to bag of words
X

array([[1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
        0, 0],
       [0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0],
       [0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0]], dtype=int64)

In [34]:
features = cv.get_feature_names()
print(features)

['another', 'day', 'fall', 'farm', 'fire', 'gold', 'haryana', 'high', 'international', 'one', 'price', 'punjab', 'rise', 'rohit', 'run', 'score', 'seven', 'sharma', 'sharp', 'smash', 't20', 'time', 'ton', 'virat']


In [35]:
df_bow = pd.DataFrame(X,columns=features)
df_bow

another  day  fall  farm  fire  gold  haryana  high  international  one  \
0        1    1     0     0     0     0        0     0              1    1   
1        0    0     0     0     0     0        0     1              1    0   
2        0    0     1     0     0     1        0     1              0    0   
3        0    0     0     1     1     0        1     0              0    0   

   ...  run  score  seven  sharma  sharp  smash  t20  time  ton  virat  
0  ...    0      0      0       0      0      1    0     0    1      1  
1  ...    1      1      0       1      0      0    1     0    0      0  
2  ...    0      0      0       0      1      0    0     0    0      0  
3  ...    0      0      1       0      0      0    0     1    0      0  

[4 rows x 24 columns]

In [36]:
# find similar sentences:
Q # my query 

'Who got highest runs in cricket'

In [37]:
#step-1---> cleaning
Q_clean= textprocess(Q)   # function is above
#step-2---> Lemmetaization
Q_lema = sent_lema(Q_clean)
#step-3 --> convert into bag of words with same dimmenssions as yours= corpus
Q_bow = cv.transform([Q_lema]).toarray()
print(Q_clean)
print(Q_lema)
print(Q_bow)

who got highest runs in cricket
get high run cricket
[[0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]]


In [38]:
X

array([[1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
        0, 0],
       [0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0],
       [0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0]], dtype=int64)

In [39]:
# cosine simmilarity
from sklearn.metrics import pairwise_distances

In [40]:
pw= pairwise_distances(X,Q_bow,metric='cosine')

In [41]:
cos=1-pw
cos

array([[0.        ],
       [0.53452248],
       [0.28867513],
       [0.        ]])

Int64Index([0, 1, 2, 3], dtype='int64')

In [42]:
ind = cos.argmax()
print('Most similarity index position {} and similarity value={}'.format(ind, cos[ind]))

Most similarity index position 1 and similarity value=[0.53452248]


In [43]:
#jacard index(intersection over union)
from sklearn.metrics import jaccard_score

In [47]:
# duplicate it then it will work
Q_bow_repeat = Q_bow.repeat(len(df),axis=0)#4---> no.of repition

In [48]:
js= jaccard_score(X.T,Q_bow_repeat.T,average=None)
js
#

array([0.        , 0.28571429, 0.14285714, 0.        ])

 ## TFIDF(Term Frequency Inverse Document Frequency)
 tfidf = log(tf+1)*log(N/df+1)

In [49]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [50]:
X_tfidf = tfidf.fit_transform(df['doc_lemma']).toarray()
X_tfidf

array([[0.38861429, 0.38861429, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.30638797, 0.38861429,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.38861429,
        0.        , 0.        , 0.38861429, 0.38861429],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.31553666, 0.31553666, 0.        ,
        0.        , 0.        , 0.        , 0.40021825, 0.40021825,
        0.40021825, 0.        , 0.40021825, 0.        , 0.        ,
        0.40021825, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.42176478, 0.        , 0.        ,
        0.42176478, 0.        , 0.3325242 , 0.        , 0.        ,
        0.42176478, 0.        , 0.42176478, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.42176478, 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.   

In [ ]:
# chatbot dataset -----> cosine simmilarities